#+title: The Time Value of Money: Single Cash Flows
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

* Motivation

What does it mean to say that money has “time value”? Essentially it means that $1 (or €1 or ¥1 or £1) promised for some future date has a different value (usually lower) than the same amount today. 

-  For example, $100 promised two years from now might be worth $90 today. By “worth” we mean that a saver (lender) would voluntarily give up $90 today in exchange for a promise (offered by the borrower) of $100 two years hence. The value today ($90) is called the present value (PV) of the amount promised ($100). And the ratio (0.9) is called the discount factor. 

-  The time value of money (TVM) is often expressed in terms of an annual interest rate (or discount rate), compounded with some frequency (typically annually or semi-annually). *Compounding* means you earn interest on interest. In the example above, the corresponding interest rate would be 5.409\% (annually compounded for two years) since $\$90(1 + 5.409\%)^2 = \$100$. 

* The Discount Rate

The TVM discount factor (or corresponding discount rate) is determined by a number of factors:

-  Supply of savings – by those wishing to shift consumption from present to future (e.g. for retirement)
-  Demand for loans – by those wishing to shift consumption from future to present (e.g. for investment)
-  Maturity (i.e. the future date when the money is due to be repaid)
-  Expected inflation (or deflation), which affects the purchasing power of cash in the future
-  Credit risk, which reflects the possibility that the loan won’t be repaid in full and on time

In this presentation, we'll cover the basic mechanics of understanding and calculating the time value of money. 

* A General Approach

Say we have \$1 today, and we can invest this dollar *every year* at 7\% per year.  

- Then at the end of 1 year we'll have $\$1(1 + 0.07) = \$1.07$
- At the end of two years we'll have $\$1.07(1 + 0.07) = \$1(1.07)(1.07) = \$1(1.07^2) = \$1.1449$
- At the end of 3 years we'll have $\$1.1449(1.07) = \$1(1.07^3) = \$1.2250$
- ...
- At the end of *n* years ...

 

* The General Formula 

Proceeding this way for *n* periods (here a period is a year), we can see the future value (*FV*) of some amount of money today (denote this as *PV*) at time *n* is:

-  $FV = PV(1 + r)^n$

-  Where we assume we can reinvest our money every year at *r*.

 

* Interactive App

The following app will calculate the future value of $1 for every year up to the maximum year you select.  You can also select the interest rate per year.  

-  Note the marked exponential increase as you increase the interest rate and number of years.  This shows the exponential effect of compounding.

-  You can also use the app to see the effect of small differences in interest rates on the future value over many years.  For example, the future value of a dollar is worth 33% more if invested for 30 years at 5% instead of 4%.

#+BEGIN_EXPORT html

<script>

var calculate = function() {

  var num = Number(document.getElementById("num").value);
  var rate = Number(document.getElementById("rate").value);
  var pv = Number(document.getElementById("pv").value);

  var fv = pv * Math.pow((1 + rate), num);
  
  document.getElementById("out_fv").innerHTML = fv.toFixed(2);

}

</script>

<body class="all">
  <h3>
    Future Value of a Single Cash Flow Calculator
  </h3>

  <div class="row">

    <div class="column">
      <table style="width:100%">
        <tr>
          <th align="left">Present Value:</th>
          <th><input id="pv" value="100" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Number of Periods:</th>
          <th><input id="num" value="10" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Rate Per Period:</th>
          <th><input id="rate" value="0.07" style="width: 50px"></th>
        </tr>
      </table>
      <button onclick="calculate()">
        Calculate.
      </button>
    </div>

    <div class="column">
    <p><b>Future Value: <span id="out_fv"></span></b></p>
    </div>

  </div>
  <br>
  <br>
  <br>
</body>

#+END_EXPORT


** Python calculation

#+BEGIN_SRC python :results output :exports both
def future_value(pv, rate, periods):
    return pv * pow(1 + rate, periods)

pv = 100
rate = 0.07
periods = 10

print(round(future_value(pv, rate, periods), 2))

#+END_SRC

#+RESULTS:
: 196.72


* Rearranging the Formula

So now that we have the general formula which describes how a single cash flow moves through time:

- $FV = PV(1 + r)^n$
 
We can now use this to solve for the *PV*, *r* and *n*.  Rearranging for the present value gives: 

- $PV = \frac{FV}{(1+r)^n}$

-  This shows that the present value decreases if the interest rate increases.  This relationship is very important in asset pricing.
-  Finding the present value is often termed *discounting*.

#+BEGIN_EXPORT html

<script>

var calculate1 = function() {

  var num1 = Number(document.getElementById("num1").value);
  var rate1 = Number(document.getElementById("rate1").value);
  var fv1 = Number(document.getElementById("fv1").value);

  var pv1 = fv1 / Math.pow((1 + rate1), num1);
  
  document.getElementById("out_pv1").innerHTML = pv1.toFixed(2);

}

</script>

<body class="all">
  <h3>
    Present Value of a Single Cash Flow Calculator
  </h3>

  <div class="row">

    <div class="column">
      <table style="width:100%">
        <tr>
          <th align="left">Future Value:</th>
          <th><input id="fv1" value="100" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Number of Periods:</th>
          <th><input id="num1" value="10" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Rate Per Period:</th>
          <th><input id="rate1" value="0.07" style="width: 50px"></th>
        </tr>
      </table>
      <button onclick="calculate1()">
        Calculate.
      </button>
    </div>

    <div class="column">
    <p><b>Present Value: <span id="out_pv1"></span></b></p>
    </div>

  </div>
  <br>
  <br>
  <br>
</body>

#+END_EXPORT

** Python Calculation

#+BEGIN_SRC python :results output :exports both
def present_value(fv, rate, periods):
    return fv / pow(1 + rate, periods)

fv = 200
rate = 0.07
periods = 10

print(round(present_value(fv, rate, periods), 2))

#+END_SRC

#+RESULTS:
: 101.67

 

* The Interest Rate

Solving our equation for the interest rate we have: 

 $r = \sqrt[n]{\frac{FV}{PV}} - 1$

- Holding other variables constant, the rate per period $r$ is increasing in $FV$ and decreasing in $PV$ and $r$.

#+BEGIN_EXPORT html

<script>

var calculate2 = function() {

  var num2 = Number(document.getElementById("num2").value);
  var pv2 = Number(document.getElementById("pv2").value);
  var fv2 = Number(document.getElementById("fv2").value);

  var rate2 = Math.pow((fv2 / pv2), (1 / num2)) - 1;
  
  document.getElementById("out_rate2").innerHTML = (100 * rate2).toFixed(2);

}

</script>

<body class="all">
  <h3>
    Interest Rate in a Single Cash Flow Calculator
  </h3>

  <div class="row">

    <div class="column">
      <table style="width:100%">
        <tr>
          <th align="left">Future Value:</th>
          <th><input id="fv2" value="200" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Present Value:</th>
          <th><input id="pv2" value="100" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Number of Periods:</th>
          <th><input id="num2" value="10" style="width: 50px"></th>
        </tr>
      </table>
      <button onclick="calculate2()">
        Calculate.
      </button>
    </div>

    <div class="column">
    <p><b>Rate Per Period: <span id="out_rate2"></span>%</b></p>
    </div>

  </div>
  <br>
  <br>
  <br>
</body>

#+END_EXPORT

** Python Calculation

#+BEGIN_SRC python :results output :exports both
def rate(fv, pv, periods):
    return pow(fv / pv, 1 / periods) - 1

fv = 200
pv = 100
periods = 10

print(str(round(100 * rate(fv, pv, periods), 2)) + "%")
#+END_SRC

#+RESULTS:
: 7.18%

 

* The Number of Periods

Lastly, solving for the number of periods yields: 

$n = \frac{ln\left(\frac{FV}{PV}\right)}{ln\left(1+r\right)}$

- Holding other variables constant, the number of periods $n$ is also increasing in $FV$, and decreasing in $PV$ and $r$.

#+BEGIN_SRC python :results output :exports both
import math

def periods(fv, pv, rate):
    return math.log(fv / pv) / math.log(1 + rate)

fv = 200
pv = 100
rate = 0.07

print(str(round(periods(fv, pv, rate), 2)) + " periods")
#+END_SRC

#+RESULTS:
: 10.24 periods


* Self-Quiz Questions


#+begin_export html
<script>
var submitAnswer1 = function() {

  var radios = document.getElementsByName('choice');
  var val= "";
  for (var i = 0, length = radios.length; i < length; i++) {
      if (radios[i].checked) {
         val = radios[i].value; 
         break;
       }
  }
  
  if (val == "" ) {
   // alert('please select choice answer');
document.getElementById("p1").innerHTML = "Choose your answer.";
document.getElementById("p1").style.backgroundColor = "white";
  } else if ( val == "Correct" ) {
//    alert('Answer is correct !');
document.getElementById("p1").innerHTML = "Correct!";
document.getElementById("p1").style.backgroundColor = "#90EE90";
  } else {
//    alert('Answer is wrong');
document.getElementById("p1").innerHTML = "Wrong";
document.getElementById("p1").style.backgroundColor = "#ff6666";
  }
};
</script>



<p>1. You bought a stock for $30 per share.  Five years later you sold it for $70 per share.  What was your annual return?</p>
<form >
<input type="radio" name="choice" value="Incorrect"> 1.14%<br>
<input type="radio" name="choice" value="Incorrect"> 8.38%<br>
<input type="radio" name="choice" value="Correct"> 18.47%<br>
<input type="radio" name="choice" value="Incorrect"> 37.12%
</form>
<button onclick="submitAnswer1()">Submit Answer</button>
<span id="p1"></span>
<br>
#+end_export


#+begin_export html
<script>
var submitAnswer2 = function() {

  var radios = document.getElementsByName('choice2');
  var val= "";
  for (var i = 0, length = radios.length; i < length; i++) {
      if (radios[i].checked) {
         val = radios[i].value; 
         break;
       }
  }
  
  if (val == "" ) {
   // alert('please select choice answer');
document.getElementById("p2").innerHTML = "Choose your answer.";
document.getElementById("p2").style.backgroundColor = "white";
  } else if ( val == "Correct" ) {
//    alert('Answer is correct !');
document.getElementById("p2").innerHTML = "Correct!";
document.getElementById("p2").style.backgroundColor = "#90EE90";
  } else {
//    alert('Answer is wrong');
document.getElementById("p2").innerHTML = "Wrong";
document.getElementById("p2").style.backgroundColor = "#ff6666";
  }
};
</script>


<br>
<p>2. Assume McCauley Ski Inc. has a 12% ROA and 20% payout ratio.  What is the maximum rate the firm can grow using only internal financing?</p>
<form >
<input type="radio" name="choice2" value="Incorrect"> -4.51%<br>
<input type="radio" name="choice2" value="Incorrect"> 0.00%<br>
<input type="radio" name="choice2" value="Correct"> 2.46%<br>
<input type="radio" name="choice2" value="Incorrect"> 12.55%
</form>
<button onclick="submitAnswer2()">Submit Answer</button>
<span id="p2"></span>
#+end_export

#+begin_export html
<script>
var submitAnswer3 = function() {

  var radios = document.getElementsByName('choice3');
  var val= "";
  for (var i = 0, length = radios.length; i < length; i++) {
      if (radios[i].checked) {
         val = radios[i].value; 
         break;
       }
  }
  
  if (val == "" ) {
   // alert('please select choice answer');
document.getElementById("p3").innerHTML = "Choose your answer.";
document.getElementById("p3").style.backgroundColor = "white";
  } else if ( val == "Correct" ) {
//    alert('Answer is correct !');
document.getElementById("p3").innerHTML = "Correct!";
document.getElementById("p3").style.backgroundColor = "#90EE90";
  } else {
//    alert('Answer is wrong');
document.getElementById("p3").innerHTML = "Wrong";
document.getElementById("p3").style.backgroundColor = "#ff6666";
  }
};
</script>


<br>
<p>3.  If a firm increases its profit margin, its IGR and SGR _______.  </p>
<form >
<input type="radio" name="choice3" value="Correct"> Increase<br>
<input type="radio" name="choice3" value="Incorrect"> Decrease<br>
<input type="radio" name="choice3" value="Incorrect"> Are unchanged
</form>
<button onclick="submitAnswer3()">Submit Answer</button>
<span id="p3"></span>
#+end_export

* [[https://en.wikipedia.org/wiki/Flesch%25E2%2580%2593Kincaid_readability_tests][Reading Ease Score]]

#+BEGIN_SRC elisp :results output :exports results
(print (writegood-reading-ease))
#+END_SRC

#+RESULTS:
: 
: "Flesch-Kincaid reading ease score: 95.31 Very easy (5th grade)"

#+BEGIN_SRC elisp :results output :exports results
(print (writegood-grade-level))
#+END_SRC

#+RESULTS:
: 
: "Flesch-Kincaid grade level score: 2.44"

 


* Original 5MF Presentation

Note, this presentation was originally here: 


